/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVerifyDebugRouteImport } from './routes/_authenticated/verify-debug'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedSolveSessionIdRouteImport } from './routes/_authenticated/solve.$sessionId'

const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyDebugRoute =
  AuthenticatedVerifyDebugRouteImport.update({
    id: '/verify-debug',
    path: '/verify-debug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolveSessionIdRoute =
  AuthenticatedSolveSessionIdRouteImport.update({
    id: '/solve/$sessionId',
    path: '/solve/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/formulas': typeof FormulasRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/verify-debug': typeof AuthenticatedVerifyDebugRoute
  '/solve/$sessionId': typeof AuthenticatedSolveSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/formulas': typeof FormulasRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/verify-debug': typeof AuthenticatedVerifyDebugRoute
  '/solve/$sessionId': typeof AuthenticatedSolveSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/formulas': typeof FormulasRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/verify-debug': typeof AuthenticatedVerifyDebugRoute
  '/_authenticated/solve/$sessionId': typeof AuthenticatedSolveSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/formulas'
    | '/history'
    | '/verify-debug'
    | '/solve/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/formulas'
    | '/history'
    | '/verify-debug'
    | '/solve/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/formulas'
    | '/_authenticated/history'
    | '/_authenticated/verify-debug'
    | '/_authenticated/solve/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FormulasRoute: typeof FormulasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify-debug': {
      id: '/_authenticated/verify-debug'
      path: '/verify-debug'
      fullPath: '/verify-debug'
      preLoaderRoute: typeof AuthenticatedVerifyDebugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solve/$sessionId': {
      id: '/_authenticated/solve/$sessionId'
      path: '/solve/$sessionId'
      fullPath: '/solve/$sessionId'
      preLoaderRoute: typeof AuthenticatedSolveSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedVerifyDebugRoute: typeof AuthenticatedVerifyDebugRoute
  AuthenticatedSolveSessionIdRoute: typeof AuthenticatedSolveSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedVerifyDebugRoute: AuthenticatedVerifyDebugRoute,
  AuthenticatedSolveSessionIdRoute: AuthenticatedSolveSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FormulasRoute: FormulasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
